DEFAULTS = {
    'max_hands': 8,
    'cash_reserve': 250,
    'travel_cost': 3.0,
    'opponent_weight': 0.8,
    'adaptive': True,
    'only_crop': None,
    'max_quadrants': 2,
    'expand_day': 7,
    'animal_target': 0,
    'animal_type': 'GOOSE',
    'water_daily': True,
    'plant_until_hour': 18,
    'sell_fraction': 1.0,
}
